#
#    Makefile for MFCX's documentation
#
#    Written by John Young, 23 September 2022
#    Copyright (c) 2022 Thistle Software
#

.PHONY: clean doc trace

doc : 
	@cd doxygen && $(MAKE) doxygen

clean:
	@cd doxygen && $(MAKE) clean

trace:
	@echo VERSION = $(VERSION)
	@echo YEAR    = $(YEAR)
